export const professions = [
  ['Архитектор', 'architect mimar meimar'],
  ['Главный архитектор проекта', 'chief architect gap'],
  ['Главный инженер проекта', 'chief project engineer gip'],
  ['Инженер-проектировщик', 'design engineer designer'],
  ['Конструктор', 'structural engineer constructor'],
  ['BIM-менеджер', 'bim manager'],
  ['BIM-координатор', 'bim coordinator'],
  ['BIM-моделлер', 'bim modeler'],
  ['CAD-специалист', 'cad specialist autocad'],
  ['Инженер ПТО', 'pto engineer technical office'],
  ['Инженер технического надзора', 'technical supervision engineer'],
  ['Инженер строительного контроля', 'construction control engineer'],
  ['Инженер авторского надзора', 'design supervision engineer'],
  ['Инженер-сметчик', 'cost estimator quantity surveyor'],
  ['Сметчик', 'estimator quantity surveyor'],
  ['Геодезист', 'surveyor geodesist'],
  ['Топограф', 'topographer'],
  ['Геолог', 'geologist'],
  ['Гидрогеолог', 'hydrogeologist'],
  ['Лаборант строительной лаборатории', 'construction laboratory technician'],
  ['Специалист по охране труда', 'occupational safety hse'],
  ['Специалист по пожарной безопасности', 'fire safety specialist'],
  ['Эколог', 'ecologist environmental specialist'],
  ['Руководитель проекта', 'project manager'],
  ['Начальник строительства', 'construction manager head'],
  ['Начальник участка', 'site manager'],
  ['Прораб', 'foreman site supervisor prorab'],
  ['Мастер строительных работ', 'construction master supervisor'],
  ['Бригадир', 'team leader brigadier'],
  ['Снабженец', 'procurement specialist buyer'],
  ['Кладовщик', 'storekeeper warehouse'],
  ['Диспетчер строительного объекта', 'construction dispatcher'],
  ['Разнорабочий', 'general worker laborer'],
  ['Подсобный рабочий', 'helper auxiliary worker'],
  ['Грузчик', 'loader porter'],
  ['Стропальщик', 'slinger rigger'],
  ['Такелажник', 'rigger'],
  ['Монтажник строительных конструкций', 'structural installer erector'],
  ['Монтажник металлоконструкций', 'steel structure installer'],
  ['Монтажник железобетонных конструкций', 'reinforced concrete installer'],
  ['Монтажник технологического оборудования', 'process equipment installer'],
  ['Монтажник фасадов', 'facade installer'],
  ['Монтажник вентилируемых фасадов', 'ventilated facade installer'],
  ['Фасадчик', 'facade worker'],
  ['Кровельщик', 'roofer'],
  ['Гидроизолировщик', 'waterproofing worker'],
  ['Теплоизолировщик', 'insulation worker'],
  ['Каменщик', 'bricklayer mason'],
  ['Бетонщик', 'concrete worker'],
  ['Арматурщик', 'rebar worker steel fixer'],
  ['Опалубщик', 'formwork carpenter'],
  ['Плотник', 'carpenter'],
  ['Столяр', 'joiner cabinetmaker'],
  ['Сварщик', 'welder kaynakci'],
  ['Газорезчик', 'gas cutter'],
  ['Слесарь строительный', 'construction fitter locksmith'],
  ['Слесарь-сантехник', 'plumber sanitary fitter'],
  ['Сантехник', 'plumber tesisatci'],
  ['Монтажник систем отопления', 'heating installer hvac'],
  ['Монтажник водоснабжения и канализации', 'water sewer installer plumbing'],
  ['Монтажник вентиляции и кондиционирования', 'hvac ventilation air conditioning installer'],
  ['Инженер ОВиК', 'hvac engineer'],
  ['Инженер ВК', 'water sewer engineer plumbing engineer'],
  ['Инженер-теплотехник', 'heating engineer thermal engineer'],
  ['Оператор теплового пункта', 'heating plant operator'],
  ['Электромонтажник', 'electrician electrical installer elektrikci'],
  ['Электрик', 'electrician elektrikci'],
  ['Инженер-электрик', 'electrical engineer'],
  ['Монтажник кабельных линий', 'cable installer'],
  ['Монтажник электрооборудования', 'electrical equipment installer'],
  ['Наладчик электрооборудования', 'electrical commissioning technician'],
  ['Слаботочник', 'low voltage technician'],
  ['Монтажник слаботочных систем', 'low current systems installer'],
  ['Инженер слаботочных систем', 'low voltage systems engineer'],
  ['Монтажник пожарной сигнализации', 'fire alarm installer aps'],
  ['Инженер пожарной сигнализации', 'fire alarm engineer aps'],
  ['Монтажник охранной сигнализации', 'security alarm installer'],
  ['Монтажник видеонаблюдения', 'cctv installer video surveillance'],
  ['Монтажник СКС', 'structured cabling installer scs'],
  ['Монтажник связи', 'telecommunications installer'],
  ['Инженер связи', 'telecommunications engineer'],
  ['Инженер АСУ ТП', 'industrial automation engineer asutp'],
  ['Инженер КИПиА', 'instrumentation automation engineer kipia'],
  ['Наладчик КИПиА', 'instrumentation commissioning technician'],
  ['Инженер-пусконаладчик', 'commissioning engineer'],
  ['Специалист ПНР', 'commissioning specialist pnr'],
  ['Машинист крана', 'crane operator'],
  ['Машинист башенного крана', 'tower crane operator'],
  ['Машинист экскаватора', 'excavator operator'],
  ['Машинист бульдозера', 'bulldozer operator'],
  ['Машинист автогрейдера', 'grader operator'],
  ['Машинист погрузчика', 'loader operator forklift'],
  ['Водитель спецтехники', 'special equipment driver'],
  ['Дорожный рабочий', 'road worker'],
  ['Асфальтобетонщик', 'asphalt worker'],
  ['Мостовщик', 'paver paving worker'],
  ['Маляр', 'painter boyaci'],
  ['Штукатур', 'plasterer'],
  ['Маляр-штукатур', 'painter plasterer'],
  ['Плиточник', 'tiler'],
  ['Облицовщик', 'cladding worker'],
  ['Отделочник', 'finishing worker'],
  ['Монтажник гипсокартона', 'drywall installer'],
  ['Монтажник натяжных потолков', 'stretch ceiling installer'],
  ['Паркетчик', 'parquet floor installer'],
  ['Укладчик напольных покрытий', 'flooring installer'],
  ['Стекольщик', 'glazier'],
  ['Монтажник окон и дверей', 'window door installer'],
  ['Ландшафтный архитектор', 'landscape architect'],
  ['Озеленитель', 'landscaper gardener'],
  ['Юрист в строительстве', 'construction lawyer legal counsel'],
  ['Бухгалтер', 'accountant'],
  ['Главный бухгалтер', 'chief accountant'],
  ['Финансовый директор', 'chief financial officer cfo'],
  ['Специалист по закупкам', 'procurement specialist purchasing'],
  ['Менеджер по продажам строительных материалов', 'building materials sales manager'],
  ['Поставщик материалов и оборудования', 'materials equipment supplier'],
  ['Независимый строительный эксперт', 'independent construction expert'],
  ['Заказчик', 'customer client developer'],
  ['Подрядчик', 'contractor'],
  ['Генеральный подрядчик', 'general contractor'],
  ['Субподрядчик', 'subcontractor']
].map(([ru, aliases]) => ({ ru, aliases }));
